### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by madnight** [byorgey/haskell-course#2]
I would like to use the website as a template for a new one, therefore i would like to know how to build the website.

**Comment by byorgey** [comment]
Sorry, I'm not going to add build instructions because (1) it is probably bitrotted and I'm not interested in spending the time getting it building again with latest versions of various packages, and (2) if I did add build instructions then I would feel responsible to keep them up to date in the future and I don't want to do that either.  If you want to try to build it anyway, you will need to install [Haskell](https://www.haskell.org/) including the `cabal` tool, and then use that to install [`shake`](http://hackage.haskell.org/package/shake) and [`hakyll`](https://jaspervdj.be/hakyll/).  Then `runhaskell Shake.hs`.  (But if you are not already familiar with Haskell tooling there's no way these instructions are sufficient; and as I said it probably doesn't build anymore.)

**Comment by madnight** [comment]
Okay thx for your fast response, i guess i'll figured it out myself then.

The update to the newest version of shake (0.16.4) is straight foward (only `system'` and `systemCWD` had to be replaced). I guess some files a missing:

```
runhaskell Shake.hs
Shake.hs: Error when running Shake build system:
* weeks/13-diagrams/13-diagrams.markdown
Error, file does not exist and no rule available:
  weeks/13-diagrams/13-diagrams.markdown
```

It seems as your shake build is expecting that every folder in weeks has a markdown file. However it is possible to delete the folders 13-diagrams and 14-QuickCheck and proceed...
